--liquibase formatted sql

--changeset ddzhukashev:1
create table refreshToken
(
    id            bigint generated by default as identity
        constraint refreshToken_pkey
            primary key,
    token varchar(255),
    userEmail     varchar(255)
);